# profile ????? ?? local
spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate ??? ?? data.sql ??

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:tc:mysql:8.0.36:///test?TC_INITSCRIPT=file:src/test/resources/schema.sql
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    database: mysql
    properties:
      hibernate:
        show-sql: true
        format_sql: true

#  sql:
#    init:
#      mode: never